### ISSUE TITLE
AbilityChoice no option for Artillery Battery

### ISSUE THREAD

**Issue by goldcarot** [doombubbles/BTD6-Mods#15]
There is no option to select a permanent but weaker version of Artillery Battery's Bombardment ability, which was added in 27.0. The page for the mod says it was updated about 3 months ago, which means it should be there. This is being run on version 28.3 using the latest version of the AbilityChoice mod.

**Comment by doombubbles** [comment]
I'm closing this issue for now as it will be addressed with an Ability Choice v2.0 overhaul that I'm working on. It likely won't be released until Mod Helper v3.0 is ready, however.
