### ISSUE TITLE
Powers In Shop Mod Locked?

### ISSUE THREAD

**Issue by GamingInfinite** [doombubbles/BTD6-Mods#2]
All the powers and abilities from the Powers in Shop mod on here are locked in the shop, like any monkey is at the beginning of the game.  This is on 27.1 with the latest melonloader version with the latest version of your mod (as of a week ago).

**Comment by doombubbles** [comment]
Thanks for the report, I believe I see the issue. Tell me if the new version of the mod fixes the problem.

**Comment by GamingInfinite** [comment]
Confirmed functions as expected.
