### ISSUE TITLE
Detailed Descriptions Not Showing Proper Info

### ISSUE THREAD

**Issue by GamingInfinite** [doombubbles/BTD6-Mods#3]
This was actually something I noticed a while ago, but wasn't sure if it was because the version of the mod I had was outdated (downloaded from nexus instead of this GitHub).  The Detailed Descriptions mod doesn't change the text to the correct information, or in most cases doesn't change it at all.  This was part of my last bug report but 27.1 of BTD6, latest version of the mod (to my knowledge) and latest version of melon loader.  The part that does change is the one that is at the top of the monkey skill area, but it changes to the same thing across all of the monkeys.  Don't know if this is a placeholder or if this is what it's supposed to say for like the dart monkey or smthn.  Included screenshots for reference
![image](https://user-images.githubusercontent.com/52724070/127781397-2281709e-9af8-4ad9-accf-6ea5975a7edd.png)
![image](https://user-images.githubusercontent.com/52724070/127781404-2c212c24-f1b4-4359-8e58-9b36db17e841.png)
![image](https://user-images.githubusercontent.com/52724070/127781440-68af8a6f-f9f3-4b99-9e2a-2c31e5feda37.png)

**Comment by doombubbles** [comment]
Yup, sorry about that. Looks like I'd just been lazy and needed to update some of my Assembly References. This new wave of updates should fix an assortment of bugs.
